name: Build And Push Docker Container

permissions:
  packages: write

on:
  push:
    tags:
      - go/*

jobs:
  send-start-message:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout
        uses: actions/checkout@v3
      # 生成镜像的标签
      - name: Build tag name
        run: echo 'TAG_NAME=${{ github.ref_name }}' | tr '/' '-' >> $GITHUB_ENV
      - name: 发送构建开始的消息到 TG
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            构建开始
            名称：MakeItAQuote TG Bot
            版本：`${{ env.TAG_NAME }}`
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout
        uses: actions/checkout@v3
      # 登录到 GitHub
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # 生成镜像的标签
      - name: Build tag name
        run: echo 'TAG_NAME=${{ github.ref_name }}' | tr '/' '-' >> $GITHUB_ENV
      # 构建和推送镜像
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/lemonnekogh/make-it-a-quote-tg:${{ env.TAG_NAME }}
            ghcr.io/lemonnekogh/make-it-a-quote-tg:go-latest
      - name: 发送构建完成的消息到 TG
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            构建并上传镜像完成
            名称：MakeItAQuote TG Bot
            版本：`${{ env.TAG_NAME }}`